sudo: required
services: 
    - docker

before-install:
    - docker build -t react-web -f Dockerfile .

script:
    - docker run react-web npm run test -- --coverage
    

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker"
    env: "ReactApp-env"
    bucket_name: "elasticbeanstalk-ap-south-1-538634141848"
    bucket_path: "reactapp"
    on:
        branch: master    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"